
var robustaData = {
	
	"projectData": {
		"name": "MatrixDSM",
		"date": "2/25/15 11:36:21 PM EET",
		"loc": "0",
		"trynumber": "8",
		"catchnumber": "8",
		"finallynumber": "0"
	},
	
	"allBadSmellData": [
	
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#52#", 
			"className": 	"InputData.java",
			"methodName": 	"read",
			"line":		"52",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#148#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"148",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#149#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"149",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#150#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"150",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#151#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"151",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#152#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"152",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#153#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"153",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#154#", 
			"className": 	"InputData.java",
			"methodName": 	"processEntities",
			"line":		"154",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#203#", 
			"className": 	"InputData.java",
			"methodName": 	"ProcessRelationships",
			"line":		"203",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#204#", 
			"className": 	"InputData.java",
			"methodName": 	"ProcessRelationships",
			"line":		"204",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#205#", 
			"className": 	"InputData.java",
			"methodName": 	"ProcessRelationships",
			"line":		"205",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/compiledinfo", 
			"codeLink":	"#/MatrixDSM/src/compiledinfo/InputData.java#218#", 
			"className": 	"InputData.java",
			"methodName": 	"processInputFile",
			"line":		"218",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/org.la4j.io", 
			"codeLink":	"#/MatrixDSM/src/org/la4j/io/AbstractStream.java#67#", 
			"className": 	"AbstractStream.java",
			"methodName": 	"closeWriter",
			"line":		"67",
			"smellType":	"Careless Cleanup"
		},
		{	"packageName": 	"src/spaningFeature", 
			"codeLink":	"#/MatrixDSM/src/spaningFeature/MultiSpanCellTable.java#84#", 
			"className": 	"MultiSpanCellTable.java",
			"methodName": 	"getToolTipText",
			"line":		"84",
			"smellType":	"Empty Catch Block"
		},
		{	"packageName": 	"src/spaningFeature", 
			"codeLink":	"#/MatrixDSM/src/spaningFeature/MultiSpanCellTableExample.java#82#", 
			"className": 	"MultiSpanCellTableExample.java",
			"methodName": 	"main",
			"line":		"82",
			"smellType":	"Unprotected Main Program"
		},
		{	"packageName": 	"src/src", 
			"codeLink":	"#/MatrixDSM/src/src/SplitPaneDSM.java#188#", 
			"className": 	"SplitPaneDSM.java",
			"methodName": 	"createAndShowGUIforFile",
			"line":		"188",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/src", 
			"codeLink":	"#/MatrixDSM/src/src/SplitPaneDSM.java#439#", 
			"className": 	"SplitPaneDSM.java",
			"methodName": 	"main",
			"line":		"439",
			"smellType":	"Unprotected Main Program"
		},
		{	"packageName": 	"src/src", 
			"codeLink":	"#/MatrixDSM/src/src/FileChooserMenu.java#155#", 
			"className": 	"FileChooserMenu.java",
			"methodName": 	"main",
			"line":		"155",
			"smellType":	"Unprotected Main Program"
		},
		{	"packageName": 	"src/tableModels", 
			"codeLink":	"#/MatrixDSM/src/tableModels/MainMatrix.java#159#", 
			"className": 	"MainMatrix.java",
			"methodName": 	"update",
			"line":		"159",
			"smellType":	"Dummy Handler"
		},
		{	"packageName": 	"src/toTest", 
			"codeLink":	"#/MatrixDSM/src/toTest/MovingJSplitPaneDivider.java#11#", 
			"className": 	"MovingJSplitPaneDivider.java",
			"methodName": 	"main",
			"line":		"11",
			"smellType":	"Unprotected Main Program"
		},
		{	"packageName": 	"src/toTest", 
			"codeLink":	"#/MatrixDSM/src/toTest/FixedColumnModel.java#15#", 
			"className": 	"FixedColumnModel.java",
			"methodName": 	"main",
			"line":		"15",
			"smellType":	"Unprotected Main Program"
		}
	]
,
	
	"allPackageData": [
		
		[
			"3",
			"src/compiledinfo",
			"0",
			"0",
			"0",
			"0",
			"0",
			"12",
			"0",
			"0",
			"12"	
		],
		[
			"9",
			"src/org.la4j.io",
			"0",
			"0",
			"0",
			"0",
			"0",
			"1",
			"0",
			"0",
			"1"	
		],
		[
			"22",
			"src/spaningFeature",
			"0",
			"1",
			"0",
			"1",
			"0",
			"0",
			"0",
			"0",
			"2"	
		],
		[
			"23",
			"src/src",
			"0",
			"0",
			"1",
			"2",
			"0",
			"0",
			"0",
			"0",
			"3"	
		],
		[
			"24",
			"src/tableModels",
			"0",
			"0",
			"1",
			"0",
			"0",
			"0",
			"0",
			"0",
			"1"	
		],
		[
			"25",
			"src/toTest",
			"0",
			"0",
			"0",
			"2",
			"0",
			"0",
			"0",
			"0",
			"2"	
		],
		[
			"0",
			"src/CodedMatrixInfo",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"1",
			"src/algorithms",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"2",
			"src/cellRenderers",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"4",
			"src/datastructure",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"5",
			"src/org.la4j",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"6",
			"src/org.la4j.decomposition",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"7",
			"src/org.la4j.factory",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"8",
			"src/org.la4j.inversion",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"10",
			"src/org.la4j.linear",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"11",
			"src/org.la4j.matrix",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"12",
			"src/org.la4j.matrix.dense",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"13",
			"src/org.la4j.matrix.functor",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"14",
			"src/org.la4j.matrix.source",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"15",
			"src/org.la4j.matrix.sparse",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"16",
			"src/org.la4j.vector",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"17",
			"src/org.la4j.vector.dense",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"18",
			"src/org.la4j.vector.functor",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"19",
			"src/org.la4j.vector.source",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"20",
			"src/org.la4j.vector.sparse",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		],
		[
			"21",
			"src/pseudomatrix",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0",
			"0"	
		]
	]
,
	
	"badSmellTypeDensity": [
		{"type": "Empty Catch Block", "count": "1"},
		{"type": "Dummy Handler", "count": "2"},
		{"type": "Unprotected Main Program", "count": "5"},
		{"type": "Nested Try Statement", "count": "0"},
		{"type": "Careless Cleanup", "count": "13"},
		{"type": "Over Logging", "count": "0"},
		{"type": "Exception Thrown From Finally Block", "count": "0"}
	]

}
